# github.com/dillacorn/awtarchy/tree/main/config/yazi
# ~/.config/yazi/yazi.toml

[mgr]
linemode = "size"

[opener]
edit = [
  { run = "/usr/bin/xdg-open %s", for = "unix", desc = "Open with default editor" },
]
