# github.com/dillacorn/awtarchy/tree/main/config/yazi
# ~/.config/yazi/yazi.toml

[mgr]
linemode = "size_and_mtime"
mouse_events = ["click", "scroll", "drag", "move"]

[opener]
edit = [
  { run = "/usr/bin/xdg-open %s", for = "unix", desc = "Open with default editor" },
]

[[plugin.prepend_fetchers]]
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
url = "*/"
run = "git"
group = "git"
