name: Temporary PowerMenu Hash

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: PowerMenu SHA256
        run: sha256sum config/quickshell/awtarchy/PowerMenu.qml
